"""
    make_table(Nc, widthmax)

Build the combined SU(Nc) coefficient table from files generated by
[`make_table3nu`](@ref) and [`make_table4`](@ref).

This function does not require MPI. It reads
`table4half_SU\$(Nc)_\$(widthmax).jld2` and
`table3nuhalf_SU\$(Nc)_\$(widthmax).jld2`, then writes
`table_SU\$(Nc)_\$(widthmax).jld2`.
"""
function make_table(Nc, widthmax)
    Nc, widthmax = _validate_table_parameters(Nc, widthmax)
    @load "table4half_SU$(Nc)_$widthmax.jld2" table4
    @load "table3nuhalf_SU$(Nc)_$widthmax.jld2" table_3ν
    tables = table_9ν(Nc, widthmax, table4, table_3ν)
    @save "table_SU$(Nc)_$widthmax.jld2" tables
end
